### ISSUE TITLE
Generator does not apply "unique" method to a field definition in migration

### ISSUE THREAD

**Issue by ja-tomasz** [webNeat/lumen-generators#31]
...although the rule gets correctly passed to the model definition

**Comment by webNeat** [comment]
Hello, Did you include `unique` in the `schema` part of the field definition ?

This will only generate the validation in the model but not in the migration
```
name:
  schema: string:50
  rules: unique|min:3
  tags: fillable
```
While this will generate both
```
name:
  schema: unique|string:50
  rules: unique|min:3
  tags: fillable
```

**Comment by ja-tomasz** [comment]
ok, good point - my overlook :)

**Comment by ja-tomasz** [comment]
hi, your solution does not work:
this:

> name:
>   schema: unique|string:50

produces:

> $table->unique|string('name', 50);

please fix.

**Comment by webNeat** [comment]
My bad, this should work
```
name:
  schema: unique string:50
  rules: unique|min:3
  tags: fillable
```
The separator is ` ` and not `|`.
Please try it
